name: CI - Feature Validation

on:
  pull_request:
    branches:
      - main
      - develop
    paths:
      - "ms-flash-card/**"
      - ".github/workflows/**"
  push:
    branches:
      - main
      - develop
    paths:
      - "ms-flash-card/**"

jobs:
  test-backend:
    runs-on: ubuntu-latest

    defaults:
      run:
        working-directory: ms-flash-card

    steps:
      - name: ğŸ§© Checkout repo
        uses: actions/checkout@v4

      - name: âš™ï¸ Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: 22 # ğŸ‘ˆ SIN cache: pnpm

      - name: ğŸ“¦ Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9
          run_install: false # instalamos deps en el siguiente paso

      - name: ğŸ“¦ Install dependencies
        run: pnpm install --frozen-lockfile

      - name: ğŸ§¹ Run ESLint
        run: pnpm lint

      - name: ğŸ§ª Run Jest tests
        run: pnpm test
